name: charja_charity
description: charja_charity


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  shared_preferences: ^2.0.15
  equatable: ^2.0.5
  dio: ^4.0.6
  graphql_flutter: ^5.0.0
  flutter_bloc: ^8.1.1
  pull_to_refresh: ^2.0.0
  flutter_screenutil: ^5.6.0
  shimmer: ^2.0.0
  simple_animations: 4.2.0
  animated_snack_bar: ^0.3.0
  awesome_dialog: ^3.0.2
  flutter_svg: ^1.1.6
  flutter_onboard: ^2.0.0
  tuple: ^2.0.1
  flutter_switch: ^0.3.2
  convex_bottom_bar: ^3.1.0+1
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  carousel_slider: ^4.2.1
  google_sign_in: ^5.4.2
  expandable: ^5.0.1
  flutter_facebook_auth: ^3.0.0
  image_picker: ^0.8.6
  intl: ^0.18.0
  file_picker: ^5.2.4
  mime: ^1.0.3
  video_player: ^2.4.10
  flutter_stripe: ^7.0.0
  change_app_package_name: ^1.1.0
  modal_bottom_sheet:


  linkedin_login: ^2.2.1

  pinput: ^2.2.16

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  mockito: ^5.1.0
  build_runner: ^2.3.2

dependency_overrides:
  freezed_annotation: ^2.0.3


flutter_icons:
 android: "launcher_icon"
 ios: true
 image_path: "assets/icons/Icon_backGround.png"


flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/locales/






  fonts:
    - family: Geometry Soft Pro
      fonts:
        - asset: assets/fonts/GeometrySoftProBoldN.otf
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jost-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Jost-Light.ttf
          weight: 300