// Mocks generated by Mockito 5.3.2 from annotations
// in charja_charity/test/features/profile/data/usecase/sp_get_event_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:charja_charity/core/data_source/model.dart' as _i35;
import 'package:charja_charity/core/errors/base_error.dart' as _i37;
import 'package:charja_charity/core/results/result.dart' as _i2;
import 'package:charja_charity/features/add_section/data/usecase/get_product_usecase.dart'
    as _i26;
import 'package:charja_charity/features/profile/data/model/delete_account_model.dart'
    as _i10;
import 'package:charja_charity/features/profile/data/model/get_my_favorite_model.dart'
    as _i31;
import 'package:charja_charity/features/profile/data/model/influncer_general_information_model.dart'
    as _i33;
import 'package:charja_charity/features/profile/data/model/profile_model.dart'
    as _i5;
import 'package:charja_charity/features/profile/data/model/sp_general_information_model.dart'
    as _i12;
import 'package:charja_charity/features/profile/data/model/SPArticleModel.dart'
    as _i23;
import 'package:charja_charity/features/profile/data/model/SPEventModel.dart'
    as _i18;
import 'package:charja_charity/features/profile/data/model/SpMediaModel.dart'
    as _i20;
import 'package:charja_charity/features/profile/data/model/SPProductsModel.dart'
    as _i16;
import 'package:charja_charity/features/profile/data/model/SPServiceModel.dart'
    as _i14;
import 'package:charja_charity/features/profile/data/model/toggle_favorite_result.dart'
    as _i27;
import 'package:charja_charity/features/profile/data/profile_repository/profile_repository.dart'
    as _i3;
import 'package:charja_charity/features/profile/data/use_case/delete_account_usecase.dart'
    as _i11;
import 'package:charja_charity/features/profile/data/use_case/edit_company_service_provider.dart'
    as _i8;
import 'package:charja_charity/features/profile/data/use_case/edit_profile_usecase.dart'
    as _i7;
import 'package:charja_charity/features/profile/data/use_case/get_my_favorite_usecase.dart'
    as _i32;
import 'package:charja_charity/features/profile/data/use_case/influncer_general_information_usecase.dart'
    as _i34;
import 'package:charja_charity/features/profile/data/use_case/influncer_get_article_usecase.dart'
    as _i25;
import 'package:charja_charity/features/profile/data/use_case/influncer_get_gallery_usecase.dart'
    as _i22;
import 'package:charja_charity/features/profile/data/use_case/profile_usecase.dart'
    as _i6;
import 'package:charja_charity/features/profile/data/use_case/social_data_usecase.dart'
    as _i9;
import 'package:charja_charity/features/profile/data/use_case/sp_general_information_usecase.dart'
    as _i13;
import 'package:charja_charity/features/profile/data/use_case/sp_get_article_usecase.dart'
    as _i24;
import 'package:charja_charity/features/profile/data/use_case/sp_get_event_usecase.dart'
    as _i19;
import 'package:charja_charity/features/profile/data/use_case/sp_get_gallery_usecase.dart'
    as _i21;
import 'package:charja_charity/features/profile/data/use_case/sp_get_products_usecase.dart'
    as _i17;
import 'package:charja_charity/features/profile/data/use_case/sp_get_services_usecase.dart'
    as _i15;
import 'package:charja_charity/features/profile/data/use_case/toggel_isAvaliable_usecase.dart'
    as _i30;
import 'package:charja_charity/features/profile/data/use_case/toogel_favorite_usecase.dart'
    as _i28;
import 'package:charja_charity/features/search/data/model/search_model.dart'
    as _i29;
import 'package:dartz/dartz.dart' as _i36;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<Data> extends _i1.SmartFake implements _i2.Result<Data> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i3.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i5.UserInfo>> getProfile(
          {required _i6.ProfileParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.Result<_i5.UserInfo>>.value(
            _FakeResult_0<_i5.UserInfo>(
          this,
          Invocation.method(
            #getProfile,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.UserInfo>>);
  @override
  _i4.Future<_i2.Result<_i5.UserInfo>> editProfile(
          {required _i7.EditProfileParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.Result<_i5.UserInfo>>.value(
            _FakeResult_0<_i5.UserInfo>(
          this,
          Invocation.method(
            #editProfile,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.UserInfo>>);
  @override
  _i4.Future<_i2.Result<_i5.Company>> editCompany(
          {required _i8.EditCompanyProfileParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #editCompany,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.Result<_i5.Company>>.value(
            _FakeResult_0<_i5.Company>(
          this,
          Invocation.method(
            #editCompany,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.Company>>);
  @override
  _i4.Future<_i2.Result<_i5.UserInfo>> update_social_media_data(
          {required _i9.SocialDataParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #update_social_media_data,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.Result<_i5.UserInfo>>.value(
            _FakeResult_0<_i5.UserInfo>(
          this,
          Invocation.method(
            #update_social_media_data,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.UserInfo>>);
  @override
  _i4.Future<_i2.Result<_i10.DeleteAccountModel>> deleteAccount(
          {required _i11.DeleteAccountParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.Result<_i10.DeleteAccountModel>>.value(
            _FakeResult_0<_i10.DeleteAccountModel>(
          this,
          Invocation.method(
            #deleteAccount,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i10.DeleteAccountModel>>);
  @override
  _i4.Future<_i2.Result<_i12.SPGeneralInformationModel>>
      get_ServiceProviderByID(
              {required _i13.SPGeneralInformationParams? params}) =>
          (super.noSuchMethod(
            Invocation.method(
              #get_ServiceProviderByID,
              [],
              {#params: params},
            ),
            returnValue:
                _i4.Future<_i2.Result<_i12.SPGeneralInformationModel>>.value(
                    _FakeResult_0<_i12.SPGeneralInformationModel>(
              this,
              Invocation.method(
                #get_ServiceProviderByID,
                [],
                {#params: params},
              ),
            )),
          ) as _i4.Future<_i2.Result<_i12.SPGeneralInformationModel>>);
  @override
  _i4.Future<_i2.Result<_i14.SPService>> getServicesById(
          {required _i15.SPGetServicesParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getServicesById,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.Result<_i14.SPService>>.value(
            _FakeResult_0<_i14.SPService>(
          this,
          Invocation.method(
            #getServicesById,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i14.SPService>>);
  @override
  _i4.Future<_i2.Result<_i16.SPProduct>> getProductsById(
          {required _i17.SPGetProductsParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsById,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.Result<_i16.SPProduct>>.value(
            _FakeResult_0<_i16.SPProduct>(
          this,
          Invocation.method(
            #getProductsById,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i16.SPProduct>>);
  @override
  _i4.Future<_i2.Result<_i18.SPEvent>> getEventById(
          {required _i19.SPGetEventParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.Result<_i18.SPEvent>>.value(
            _FakeResult_0<_i18.SPEvent>(
          this,
          Invocation.method(
            #getEventById,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i18.SPEvent>>);
  @override
  _i4.Future<_i2.Result<_i20.SPGallery>> getSPGalleryById(
          {required _i21.SPGetGalleryParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSPGalleryById,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.Result<_i20.SPGallery>>.value(
            _FakeResult_0<_i20.SPGallery>(
          this,
          Invocation.method(
            #getSPGalleryById,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i20.SPGallery>>);
  @override
  _i4.Future<_i2.Result<_i20.SPGallery>> getInfluncerGalleryById(
          {required _i22.InfluncerGetGalleryParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInfluncerGalleryById,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.Result<_i20.SPGallery>>.value(
            _FakeResult_0<_i20.SPGallery>(
          this,
          Invocation.method(
            #getInfluncerGalleryById,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i20.SPGallery>>);
  @override
  _i4.Future<_i2.Result<_i23.SPArticleModel>> getArticleById(
          {required _i24.SPGetArticleParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticleById,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.Result<_i23.SPArticleModel>>.value(
            _FakeResult_0<_i23.SPArticleModel>(
          this,
          Invocation.method(
            #getArticleById,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i23.SPArticleModel>>);
  @override
  _i4.Future<_i2.Result<_i23.SPArticleModel>> getInfluncerArticleByID(
          {required _i25.InfluncerGetArticleParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInfluncerArticleByID,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.Result<_i23.SPArticleModel>>.value(
            _FakeResult_0<_i23.SPArticleModel>(
          this,
          Invocation.method(
            #getInfluncerArticleByID,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i23.SPArticleModel>>);
  @override
  String urlAccordingType({required _i26.GetProductParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #urlAccordingType,
          [],
          {#params: params},
        ),
        returnValue: '',
      ) as String);
  @override
  String getModelKeyForServiceProvider() => (super.noSuchMethod(
        Invocation.method(
          #getModelKeyForServiceProvider,
          [],
        ),
        returnValue: '',
      ) as String);
  @override
  _i4.Future<_i2.Result<_i27.ToggleFavoriteResult>> toggleFavorite(
          {required _i28.ToggleFavoriteParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.Result<_i27.ToggleFavoriteResult>>.value(
            _FakeResult_0<_i27.ToggleFavoriteResult>(
          this,
          Invocation.method(
            #toggleFavorite,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i27.ToggleFavoriteResult>>);
  @override
  _i4.Future<_i2.Result<_i29.SearchOfServiceProvider>> toggleIsAvailable(
          {required _i30.ToggleIsAvaliableParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleIsAvailable,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.Result<_i29.SearchOfServiceProvider>>.value(
            _FakeResult_0<_i29.SearchOfServiceProvider>(
          this,
          Invocation.method(
            #toggleIsAvailable,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i29.SearchOfServiceProvider>>);
  @override
  _i4.Future<_i2.Result<_i31.GetMyFavoriteListModel>> getMyFavorite(
          {required _i32.GetMyFavoriteParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyFavorite,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.Result<_i31.GetMyFavoriteListModel>>.value(
            _FakeResult_0<_i31.GetMyFavoriteListModel>(
          this,
          Invocation.method(
            #getMyFavorite,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i31.GetMyFavoriteListModel>>);
  @override
  _i4.Future<
      _i2.Result<_i33.InfluncerGeneralInformationModel>> get_InfluncerById(
          {required _i34.InfluncerGeneralInformationParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #get_InfluncerById,
          [],
          {#params: params},
        ),
        returnValue:
            _i4.Future<_i2.Result<_i33.InfluncerGeneralInformationModel>>.value(
                _FakeResult_0<_i33.InfluncerGeneralInformationModel>(
          this,
          Invocation.method(
            #get_InfluncerById,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i33.InfluncerGeneralInformationModel>>);
  @override
  String getModelKeyForInfluncer() => (super.noSuchMethod(
        Invocation.method(
          #getModelKeyForInfluncer,
          [],
        ),
        returnValue: '',
      ) as String);
  @override
  _i2.Result<Model> call<Model extends _i35.BaseModel>(
          {required _i36.Either<_i37.BaseError, _i35.BaseModel>? result}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#result: result},
        ),
        returnValue: _FakeResult_0<Model>(
          this,
          Invocation.method(
            #call,
            [],
            {#result: result},
          ),
        ),
      ) as _i2.Result<Model>);
  @override
  _i2.Result<List<Model>> paginatedCall<Model extends _i35.BaseModel>(
          {required _i36.Either<_i37.BaseError, _i35.BaseModel>? result}) =>
      (super.noSuchMethod(
        Invocation.method(
          #paginatedCall,
          [],
          {#result: result},
        ),
        returnValue: _FakeResult_0<List<Model>>(
          this,
          Invocation.method(
            #paginatedCall,
            [],
            {#result: result},
          ),
        ),
      ) as _i2.Result<List<Model>>);
  @override
  _i2.Result<bool> noModelCall(
          {required _i36.Either<_i37.BaseError, bool>? result}) =>
      (super.noSuchMethod(
        Invocation.method(
          #noModelCall,
          [],
          {#result: result},
        ),
        returnValue: _FakeResult_0<bool>(
          this,
          Invocation.method(
            #noModelCall,
            [],
            {#result: result},
          ),
        ),
      ) as _i2.Result<bool>);
}
